version: "3.9"

services:
  master:
    build: ./packages/master
    volumes:
      - "./server.config.yaml:/usr/src/replicated-log/server.config.yaml"
      - "./slave-services.config.yaml:/usr/src/replicated-log/slave-services.config.yaml"
    ports:
      - "3000:3000"
    depends_on:
      - slave-1
      - slave-2
  slave-1:
    build: ./packages/slave
    volumes:
      - "./slave-1.config.yaml:/usr/src/replicated-log/server.config.yaml"
    ports:
      - "3001:3000"
  slave-2:
    build: ./packages/slave
    volumes:
      - "./slave-2.config.yaml:/usr/src/replicated-log/server.config.yaml"
    ports:
      - "3002:3000"
